// Hub Worker for games.csiesheep.com. It OWNS the subdomain root: it serves
// the landing page (index.html, via static assets) and the domain-root files
// that belong to the whole subdomain, not to any single game.
//
// Each individual game is a separate Worker attached by a more-specific Route
// (e.g. games.csiesheep.com/betrayal_sound_board/*). Cloudflare matches the
// most-specific route first, so those game paths peel off to their own Workers
// and everything else — including "/" — falls through to this hub.
//
// `run_worker_first: true` (wrangler.jsonc) lets this script answer the root
// files before the static-asset handler runs.

const ORIGIN = "https://games.csiesheep.com";

// Google requires ads.txt at the domain root to authorise AdSense for the
// whole subdomain (one file covers every game underneath it). Whatever
// publisher id is listed here must match the ca-pub-... the pages actually
// request ads with, or Google withholds creatives.
const ADS_TXT =
  "#ads.txt generated by Easy Google AdSense plugin\n" +
  "google.com, pub-1718750784240290, DIRECT, f08c47fec0942fa0\n";

// Cloudflare's Managed robots.txt is prepended to this response and supplies
// the crawl rules already; we only add the Sitemap directives so we don't emit
// a duplicate "User-agent: *" group.
//
// Two directives, because robots.txt permits any number of them and this is
// the only thing that points a crawler at the prefix-scoped sitemap. The root
// sitemap below carries one line per game — the landing pages — while Grave
// Errand's own sitemap covers its five inner pages. Without this second line
// nothing links to it and those pages are reachable only by crawling links.
const ROBOTS_TXT =
  "Sitemap: " + ORIGIN + "/sitemap.xml\n" +
  "Sitemap: " + ORIGIN + "/zombie_in_the_pocket/sitemap.xml\n" +
  "Sitemap: " + ORIGIN + "/jiangshi_in_the_pocket/sitemap.xml\n" +
  "Sitemap: " + ORIGIN + "/tiandihui/sitemap.xml\n" +
  "Sitemap: " + ORIGIN + "/last_train/sitemap.xml\n" +
  "Sitemap: " + ORIGIN + "/zongheng/sitemap.xml\n";

// The one sitemap for the whole subdomain. Add a line per game as it launches.
//
// Only the landing page of each game goes here. Grave Errand serves its own
// prefix-scoped sitemap covering its five pages
// (/zombie_in_the_pocket/sitemap.xml), which this document cannot reference:
// a <urlset> and a <sitemapindex> are different documents and mixing them is
// invalid. robots.txt is where the two are tied together — see ROBOTS_TXT
// above, which lists both — so the inner pages no longer depend on a crawler
// following links from the landing page to be found.
// lastmod is the date that site's content last changed, taken from the last
// commit touching pages or assets in its repo -- not the date this file was
// edited. Each game lives in a separate repo and Worker, so this hub cannot
// read those dates at runtime; they are hand-maintained and will drift again.
// Google ignores lastmod wholesale once it finds it unreliable, so a wrong
// date is worse than none: if these stop being updated, delete the field
// rather than leave it stale.
// The front page is listed twice, once per language. Each version names the
// other through <link rel="alternate" hreflang> in index.html; listing both
// here just makes sure a crawler finds the Chinese one without following them.
const SITEMAP_URLS = [
  { loc: ORIGIN + "/", lastmod: "2026-09-17", priority: "1.0" },
  { loc: ORIGIN + "/?lang=zh-Hant", lastmod: "2026-09-17", priority: "1.0" },
  { loc: ORIGIN + "/betrayal_sound_board/", lastmod: "2026-08-29", priority: "0.9" },
  { loc: ORIGIN + "/zombie_in_the_pocket/", lastmod: "2026-08-21", priority: "0.9" },
  { loc: ORIGIN + "/jiangshi_in_the_pocket/", lastmod: "2026-08-29", priority: "0.9" },
  { loc: ORIGIN + "/elevator_inc/", lastmod: "2026-09-04", priority: "0.9" },
  { loc: ORIGIN + "/dice_war/", lastmod: "2026-09-11", priority: "0.9" },
  { loc: ORIGIN + "/tiandihui/", lastmod: "2026-09-12", priority: "0.9" },
  { loc: ORIGIN + "/last_train/", lastmod: "2026-09-16", priority: "0.9" },
  { loc: ORIGIN + "/zongheng/", lastmod: "2026-09-22", priority: "0.9" },
];
const SITEMAP_XML =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  SITEMAP_URLS.map(
    (u) =>
      "  <url>\n" +
      "    <loc>" + u.loc + "</loc>\n" +
      "    <lastmod>" + u.lastmod + "</lastmod>\n" +
      "    <priority>" + u.priority + "</priority>\n" +
      "  </url>\n"
  ).join("") +
  "</urlset>\n";

// TODO: when you create the Search Console property for games.csiesheep.com,
// add its verification file path here (serve it directly, as the betrayal
// repo does, so the static-asset .html redirect doesn't interfere).

function text(body, type = "text/plain; charset=utf-8") {
  return new Response(body, { headers: { "content-type": type } });
}

// ---- The Chinese front page ------------------------------------------------
//
// index.html carries both languages and switches between them in the browser,
// so to a crawler that runs no script -- and to a link preview, which never
// does -- there is only one page, and it is English. /?lang=zh-Hant is the
// Chinese one made real: the same file, with <html lang> and the head
// rewritten here before it leaves. The body needs nothing -- its CSS shows the
// Chinese half whenever <html lang="zh-Hant">.
//
// Only this exact value. ?lang=en and every other query get the English page
// untouched, whose canonical already points at "/".
const ZH = "zh-Hant";
const ZH_URL = ORIGIN + "/?lang=" + ZH;
const ZH_HEAD = {
  title: "csiesheep 的遊戲 — 免費的瀏覽器桌遊與小工具",
  description: "csiesheep 做的免費瀏覽器桌遊與桌遊小幫手。不用安裝，不用註冊。",
  ogTitle: "csiesheep 的遊戲",
  ogDescription: "免費的瀏覽器桌遊與桌遊小幫手。不用安裝，不用註冊。",
};

function set(attr, value) {
  return { element(e) { e.setAttribute(attr, value); } };
}

function toChinese(res) {
  const type = res.headers.get("content-type") || "";
  if (res.status !== 200 || !type.includes("text/html")) return res;

  const out = new HTMLRewriter()
    .on("html", set("lang", ZH))
    .on("title", { element(e) { e.setInnerContent(ZH_HEAD.title); } })
    .on('meta[name="description"]', set("content", ZH_HEAD.description))
    .on('link[rel="canonical"]', set("href", ZH_URL))
    .on('meta[property="og:url"]', set("content", ZH_URL))
    .on('meta[property="og:title"]', set("content", ZH_HEAD.ogTitle))
    .on('meta[property="og:description"]', set("content", ZH_HEAD.ogDescription))
    .on('meta[property="og:locale"]', set("content", "zh_TW"))
    .on('meta[property="og:locale:alternate"]', set("content", "en_US"))
    // The sheep's alt text, for readers that never run the page's script.
    .on("img.hub-mark", { element(e) { const zh = e.getAttribute("data-alt-zh"); if (zh) e.setAttribute("alt", zh); } })
    .transform(res);

  // The asset's ETag describes the English bytes. These are not those bytes,
  // so it must not be offered back for a 304.
  const headers = new Headers(out.headers);
  headers.delete("etag");
  return new Response(out.body, { status: out.status, headers });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/ads.txt") return text(ADS_TXT);
    if (url.pathname === "/robots.txt") return text(ROBOTS_TXT);
    if (url.pathname === "/sitemap.xml") return text(SITEMAP_XML, "application/xml; charset=utf-8");

    const res = await env.ASSETS.fetch(request);
    if (url.pathname === "/" && url.searchParams.get("lang") === ZH) return toChinese(res);
    return res;
  },
};
